name: Run Python Script with Secret

on: 
  workflow_dispatch:
env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Python script   
      run:
        python Streamlit_Script.py
